// <auto-generated />
using ApiCodeSnippets.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCodeSnippets.Migrations
{
    [DbContext(typeof(CodeSnippetsContext))]
    [Migration("20240913123011_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiCodeSnippets.Models.CodeSnippet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgrammingLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Snippet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeSnippets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Simple sum function snippet",
                            ProgrammingLanguage = "TypeScript",
                            Snippet = "const sum = (x, y) => {return x + y;}",
                            Status = "Active",
                            Tag = "Functions",
                            Title = "Sum function"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Simple multiply function snippet",
                            ProgrammingLanguage = "TypeScript",
                            Snippet = "const multiply = (x, y) => {return x * y;}",
                            Status = "Active",
                            Tag = "Functions",
                            Title = "Multiply function"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
